### ISSUE TITLE
RFE: Expose gmp_version()

### ISSUE THREAD

**Issue by FGasper** [pjacklam/p5-Math-BigInt-GMP#3]
I’m seeing bizarre failures with Crypt::Perl that _look_ like GMP blowing up somehow.

Example: http://www.cpantesters.org/cpan/report/e385ecb6-51ae-11ec-a7b3-548e1f24ea8f

It would be a bit easier to diagnose this if Math::BigInt::GMP exposed the underlying GMP version.

I’m happy to submit a PR if you’d like.

Thank you!

**Comment by pjacklam** [comment]
Yes, please provide a PR. Thank you.
